.nh
.TH "gh" "1" "Aug 2021" "" ""

.SH NAME
.PP
gh\-browse \- Open the repository in the browser


.SH SYNOPSIS
.PP
\fBgh browse [ | ] [flags]\fP


.SH DESCRIPTION
.PP
Open the GitHub repository in the web browser.


.SH OPTIONS
.PP
\fB\-b\fP, \fB\-\-branch\fP=""
	Select another branch by passing in the branch name

.PP
\fB\-n\fP, \fB\-\-no\-browser\fP[=false]
	Print destination URL instead of opening the browser

.PP
\fB\-p\fP, \fB\-\-projects\fP[=false]
	Open repository projects

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format

.PP
\fB\-s\fP, \fB\-\-settings\fP[=false]
	Open repository settings

.PP
\fB\-w\fP, \fB\-\-wiki\fP[=false]
	Open repository wiki


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH EXAMPLE
.PP
.RS

.nf
$ gh browse
#=> Open the home page of the current repository

$ gh browse 217
#=> Open issue or pull request 217

$ gh browse \-\-settings
#=> Open repository settings

$ gh browse main.go:312
#=> Open main.go at line 312

$ gh browse main.go \-\-branch main
#=> Open main.go in the main branch


.fi
.RE


.SH SEE ALSO
.PP
\fBgh(1)\fP
