.nh
.TH "gh" "1" "Aug 2021" "" ""

.SH NAME
.PP
gh\-extension\-list \- List installed extension commands


.SH SYNOPSIS
.PP
\fBgh extension list [flags]\fP


.SH DESCRIPTION
.PP
List installed extension commands


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-extension(1)\fP
