.nh
.TH "gh" "1" "Aug 2021" "" ""

.SH NAME
.PP
gh\-extension\-create \- Create a new extension


.SH SYNOPSIS
.PP
\fBgh extension create  [flags]\fP


.SH DESCRIPTION
.PP
Create a new extension


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-extension(1)\fP
