.nh
.TH "gh" "1" "Aug 2021" "" ""

.SH NAME
.PP
gh\-extension\-upgrade \- Upgrade installed extensions


.SH SYNOPSIS
.PP
\fBgh extension upgrade { | \-\-all} [flags]\fP


.SH DESCRIPTION
.PP
Upgrade installed extensions


.SH OPTIONS
.PP
\fB\-\-all\fP[=false]
	Upgrade all extensions

.PP
\fB\-\-force\fP[=false]
	Force upgrade extension


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-extension(1)\fP
