.nh
.TH "gh" "1" "Aug 2021" "" ""

.SH NAME
.PP
gh\-extension\-install \- Install a gh extension from a repository


.SH SYNOPSIS
.PP
\fBgh extension install  [flags]\fP


.SH DESCRIPTION
.PP
Install a gh extension from a repository


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-extension(1)\fP
