.nh
.TH "gh" "1" "Aug 2021" "" ""

.SH NAME
.PP
gh\-extension\-remove \- Remove an installed extension


.SH SYNOPSIS
.PP
\fBgh extension remove  [flags]\fP


.SH DESCRIPTION
.PP
Remove an installed extension


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-extension(1)\fP
