.nh
.TH "gh" "1" "Aug 2021" "" ""

.SH NAME
.PP
gh\-extension \- Manage gh extensions


.SH SYNOPSIS
.PP
\fBgh extension [flags]\fP


.SH DESCRIPTION
.PP
GitHub CLI extensions are repositories that provide additional gh commands.

.PP
The name of the extension repository must start with "gh\-" and it must contain an
executable of the same name. All arguments passed to the \fB\fCgh <extname>\fR invocation
will be forwarded to the \fB\fCgh\-<extname>\fR executable of the extension.

.PP
An extension cannot override any of the core gh commands.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-extension\-create(1)\fP, \fBgh\-extension\-install(1)\fP, \fBgh\-extension\-list(1)\fP, \fBgh\-extension\-remove(1)\fP, \fBgh\-extension\-upgrade(1)\fP
